// DO NOT EDIT. Code generated by 'cdktf convert' - Please report bugs at https://cdk.tf/bug
import { App } from "cdktf";
import { BackendStack } from "./src/backend";

/*
 * Provider bindings are generated by running `cdktf get`.
 * See https://cdk.tf/provider-generation for more details.
 */

const app = new App();
new BackendStack(app,"iac-assignment-backend");
app.synth();
